name: Question 7 Workflow

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Cache dependencies
      id: cache-step
      uses: actions/cache@v4
      with:
        path: ~/.npm
        key: cache-3f17a5b

    - name: prime-cache-3f17a5b
      if: always()
      run: |
        echo "Cache Hit: ${{ steps.cache-step.outputs.cache-hit }}"
        if [ "${{ steps.cache-step.outputs.cache-hit }}" == 'true' ]; then
          echo "Hit"
        else
          echo "Miss"
        fi
